top_srcdir   = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
top_builddir = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
srcdir       = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules/generators
builddir     = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules/generators
VPATH        = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules/generators

include $(top_srcdir)/build/special.mk

