top_srcdir   = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
top_builddir = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
srcdir       = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/os/unix
builddir     = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/os/unix
VPATH        = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
