top_srcdir   = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
top_builddir = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
srcdir       = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules
builddir     = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules
VPATH        = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

