top_srcdir   = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
top_builddir = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
srcdir       = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules/http
builddir     = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules/http
VPATH        = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules/http

include $(top_srcdir)/build/special.mk

