top_srcdir   = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
top_builddir = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
srcdir       = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/server/mpm/prefork
builddir     = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/server/mpm/prefork
VPATH        = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
