top_srcdir   = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
top_builddir = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
srcdir       = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules/experimental
builddir     = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules/experimental
VPATH        = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/modules/experimental
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
