top_srcdir   = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
top_builddir = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
srcdir       = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/server/mpm
builddir     = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/server/mpm
VPATH        = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
