top_srcdir   = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
top_builddir = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31
srcdir       = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/os
builddir     = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/os
VPATH        = /home/adam/Documents/db-prov-2015/src/httpd-execution-partitions-2.2.31/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
